version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
    - 11.2.3
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.0
    - 12.6.2
  - dependency-name: firebase
    versions:
    - 8.2.1
    - 8.2.5
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.8
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
